config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cruises
  resources :bookings, only: [:index, :create, :show, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :cruise
  belongs_to :user

  has_many :users
  has_many :cruises

  validates :total_price, :schedule_date, :available_seats, presence: true
end

app/models/cruise.rb
class Cruise < ApplicationRecord
  belongs_to :user
  has_many   :bookings

  validates :name, uniqueness: true, presence: true
  validates :location, :capacity, :duration_of_cruise, presence: true
  validates :price, numericality: { only_integer: true }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :cruises

  # validates :username, uniqueness: true, presence: true
  # validates :phone_number, uniqueness: true, presence: true, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed."}

  # validates :address, presence: true
  # validates :email, format: { with: /\A.*@.*\.com\z/ }
  # validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @cruise = Cruise.find(params[:booking][:cruise_id])
    @booking = Booking.new(booking_params)
    @booking.schedule_date = get_booking_date(booking_params)
    @booking.available_seats = @cruise.capacity - Booking.all.count
    @booking.user = current_user
    if @booking.save
      flash[:notice] = 'Booking has been successfully recorded'
      redirect_to cruises_path
    else
      render 'cruises/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @cruise = Cruise.find(@booking.cruise_id)
    if Booking.delete(params[:id]).positive?
      flash[:notice] = "Your booking for #{@cruise.name} has been successfully cancelled !"
    else
      flash[:error] = 'Sorry something went wrong, please try again!'
    end
    redirect_to bookings_path
  end

  private

  def get_booking_date(params)
    "#{params["schedule_date(3i)"]}/#{params["schedule_date(2i)"]}/#{params["schedule_date(1i)"]}"
  end

  def booking_params
    params.require(:booking).permit(:total_price, :cruise_id, :schedule_date)
  end
end

app/controllers/cruises_controller.rb
class CruisesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @cruises = Cruise.all
  end

  def new
    @cruise = Cruise.new
  end

  def show
    @cruise = Cruise.find(params[:id])
    @booking = Booking.new
  end

  def create
    @cruise = Cruise.new(cruise_params)
    @cruise.save
    redirect_to cruise_path(@cruise)
  end

  def update
    @cruise = Cruise.find(params[:id])
    @cruise.update(cruise_params)
    flash[:notice] = 'Cruise information has been updated'
    redirect_to cruise_path
  end

  def destroy
    @cruise.destroy
    redirect_to cruises_path
  end

  private

  def set_cruise
    @cruise = Cruise.find(params[:id])
  end

  def cruise_params
    params.require(:cruise).permit(:name, :description, :duration_of_cruise,
                                   :capacity, :extra_offers, :cancellation_policy, :location, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @bookings = Booking.all
    @fidelity_point = 0
    @bookings.each do |booking|
      @fidelity_point += (booking.total_price / 100) * 10 if booking.user == current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@cruise, @booking]) do |f| %>
  <div class="form-inputs">
    <%=  f.hidden_field :total_price, :value => @cruise.price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<h1>my booking list</h1>
<div class="d-flex row justify-content-center">
  <% @bookings.each do |booking| %>
    <% if (booking.user_id == current_user.id) %>
      <div class="col-lg-2 h-5 justify-content-center m-2">
        <div class="card bg-light">
          <div class="card-body d-flex justify-content-between">
            <h5 class="card-title fw-bolder"><%= booking.cruise.name %> </h5>
             <%= link_to booking_path(booking), method: :delete do %> 
             <i class="fas fa-trash-alt"></i>
             <% end %>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Cancellation Policy: <%= booking.cruise.cancellation_policy %></li>
            <li class="list-group-item"> Location: <%= booking.cruise.location %></li>
            <li class="list-group-item"> schedule date: <%= booking.schedule_date %></li>
            <li class="list-group-item"> Price: Rs<%= booking.cruise.price.to_i %></li>
          </ul>
        </div>
      </div>
    <% elsif current_user.is_owner? %>
      <div class="col-lg-2 h-5 justify-content-center m-2">
        <div class="card bg-light">
          <div class="card-body">
            <h5 class="card-title"> <%= booking.cruise.name %> </h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Cancellation Policy: <%= booking.cruise.cancellation_policy %></li>
            <li class="list-group-item"> Location: <%= booking.cruise.location %></li>
            <li class="list-group-item"> Schedule date: <%= booking.schedule_date %></li>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="card-body d-flex justify-content-center">
    <%= link_to "Back To Cruise List",  cruises_path, class: "btn btn-booknow card-link"%>
    <%= link_to "Home",  root_path, class: "btn btn-booknow card-link"%>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container" style= "height: 65vh;">
  <h1>Congratulations!</h1>
  <h4>You have confirmed your booking for <%=  @cruise.name %></h4>
  <h4>Please go to your profile to check your fidelity points</h4>
</div>

app/views/bookings/show.html.erb
<h1>my booking show</h1>

app/views/cruises/_form.html.erb
<h2>into simple form</h2>

app/views/cruises/index.html.erb
<div class="container">
  <h1>Our <span>Cruise</span> list</h1>
    <h4>Take a look at our best offers and travel destinations:</h4>
  <div class="d-flex row justify-content-center">
    <% @cruises.each do |cruise| %> 
      <div class="col-lg-4">
        <div class="card bg-light my-3">
          <%= image_tag(cruise.image_url, height: 300) %>
          <div class="card-body d-flex align-items-center"> 
            <div class="">
              <h5 class="card-title fw-bolder"> <%= cruise.name %> </h5>
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"> Location: <%= cruise.location %></li>
            <li class="list-group-item"> Price: Rs<%= cruise.price.to_i %></li>
          </ul>
          <div class="card-body">
            <%= link_to "Enquire",  cruise_path(cruise), class: "btn btn-booknow card-link"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/cruises/new.html.erb
<% if current_user.is_owner? %>
  <h1>Insert a new cruise page</h1>
  <%= render 'form' %>
<% else %>
  <% render 'shared/flashes' %>
<% end %>

app/views/cruises/show.html.erb
<div class="d-flex justify-content-center align-items-start" style="height: 100vh; background-position: center; background-size: cover; background-repeat: no-repeat; background-image: url('<%= @cruise.image_url %>')">

  <div class="card py-3 px-5" style="opacity: 0.9; margin-top: 5rem; margin-left: 10rem; max-width: 1024px">
    <h1 style="font-size: 1.5rem; margin-top: 0;"><%= @cruise.name %></h1>
    <%= simple_form_for(@booking) do |f| %>
      <%= f.hidden_field :total_price, :value => @cruise.price %>
      <%= f.hidden_field :cruise_id, :value => @cruise.id %>
      <%= f.input :schedule_date, as: :date,
                    start_year: Date.today.year,
                    end_year: Date.today.year+1, discard_day: false,
                    order: [:day, :month, :year] %>
      <%= f.button :submit, class: "btn btn-booknow", value: "Confirm Booking" %>
      <%= link_to "Back",  cruises_path, class: "btn btn-secondary" %>
    <% end %>
    <br>
    <div>    
      <%= @cruise.description %>
    </div>
    <div>
      <h2 class="cruise-heading">Extra Offers</h2>
      <%= @cruise.extra_offers %>
    </div>
    <div>
      <h2 class="cruise-heading">Cancellation Policy</h2>
      <%= @cruise.cancellation_policy %>
    </div>
    <br>
  </div>
  <div class="d-flex flex-column justify-content-center align-items-start" style="margin-top: -1rem;">
    <div class="cruise-options">
      <i class="fas fa-stopwatch" ></i>
      <h3>Duration</h3>
      <span>
        <%= @cruise.duration_of_cruise %>
      </span>
    </div>
    <div class="cruise-options">
      <i class="fas fa-map-marked-alt" ></i>
      <h3>Departure</h3>
      <span>
        <%= @cruise.location %>
      </span>
    </div>
    <div class="cruise-options">
      <i class="far fa-credit-card" ></i>
      <h3>Price</h3>
      <span>
        Rs <%= @cruise.price.to_i %>
      </span>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParadiseCruise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,700;1,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Andada+Pro&family=Poppins:ital,wght@1,700;1,800&display=swap" rel="stylesheet">
  <body>
    <%= render 'shared/navbar' %>
    <div class="container d-flex justify-content-center">
        <%= render 'shared/flashes', class: "alert w-50" %>
    </div>
    <div>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body> 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

app/views/pages/_imagesvg.html.erb
<svg id="svg-office" class="Hero__image-grid anim-hero" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 590.91 632.66">
  <defs>
    <clipPath id="heroclip1">
      <rect class="hero__swipe-1" id="heroclip1Rect" x="101.31" y="51.24" width="488.79" height="221.87" fill="#fff" data-svg-origin="590.1000061035156 162.17499923706055" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>
    </clipPath>

    <clipPath id="heroclip2">
      <rect class="hero__swipe-2" id="heroclip1Rect" x="195.36" y="293.94" width="292.4" height="268.6" fill="#fff" data-svg-origin="487.75999450683594 428.24000549316406" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>
    </clipPath>

    <clipPath id="heroclip3">
      <rect class="hero__swipe-3" id="heroclip3Rect" x="1.73" y="233.41" width="174.53" height="162.61" fill="#fff" data-svg-origin="176.25999879837036 314.71500396728516" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>
    </clipPath>

    <clipPath id="heroclip4">
      <rect class="hero__swipe-4" id="heroclip4Rect" x="100.03" y="405.79" width="75.83" height="73.12" fill="#fff" data-svg-origin="175.86000061035156 442.3500099182129" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>
    </clipPath>

  </defs>
  <g class="fouc fouc--hero" opacity="0" data-svg-origin="591 314.5249938964844" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px; opacity: 1;">
    <circle class="hero__circle" cx="90.18" cy="79.56" r="50" fill="#dae1e2" data-svg-origin="90.18000030517578 79.55999755859375" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px; opacity: 1;"></circle>
    <circle class="hero__circle" cx="488.39" cy="563.49" r="30" fill="#23d8a0" data-svg-origin="488.3900146484375 563.489990234375" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px; opacity: 1;"></circle>

    <rect class="hero__swipe-1" x="102" y="52" width="488" height="220" fill="#23d8a0" data-svg-origin="590 162" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>
    <rect class="hero__swipe-2" x="196" y="294" width="292" height="268" fill="#FAFAFA" data-svg-origin="488 428" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>
    <rect class="hero__swipe-3" x="2" y="234" width="173" height="162" fill="#FAFAFA" data-svg-origin="175 315" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>
    <rect class="hero__swipe-4" x="101" y="406" width="75" height="73" fill="#23d8a0" data-svg-origin="176 442.5" transform="matrix(1,0,0,1,0,0)" style="transform-origin: 0px 0px;"></rect>

    <image clip-path="url(#heroclip1)" href="https://images.unsplash.com/photo-1564069114553-7215e1ff1890?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80" preserveAspectRatio="xMidYMid slice" x="101" y="51" width="490" height="223"></image>
    <image clip-path="url(#heroclip2)" href="https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" preserveAspectRatio="xMidYMid slice" x="195" y="293" width="294" height="270"></image>
    <image clip-path="url(#heroclip3)" href="https://images.unsplash.com/photo-1517048676732-d65bc937f952?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80" preserveAspectRatio="xMidYMid slice" x="1" y="233" width="176" height="164"></image>
    <image clip-path="url(#heroclip4)" href="https://images.unsplash.com/photo-1556761175-b413da4baf72?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=967&q=80" preserveAspectRatio="xMidYMid slice" x="99" y="404" width="78" height="76"></image>
  </g>
</svg>

app/views/pages/home.html.erb
<div class ="container d-flex flex-column align-items-center justify-content-center">

  <h1 id="header">Welcome to <span>Paradise Cruises Mauritius</span></h1>


  <div class= "d-flex flex-row justify-content-evenly ml-5 my-5 flex-basis">
    <div class="carousel-container">
      <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= cl_image_tag("cruise/beautiful-boat-ocean-paradise-wallpaper-preview_byncgm", height: "400", width: "600", class: "d-block carousel-image") %>
              <div class="carousel-caption d-none d-md-block">
                <p> May your adventures bring you closer together, even as they take you far away from home. </p>
              </div>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag( "cruise/zil-cruise-cover-1024x683_ahto2d", height: "400", width: "600", class: "d-block carousel-image") %>
              <div class="carousel-caption d-none d-md-block">
                <p> Explore the world with our greatest offers, make memories on the paradise island.</p>
              </div>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag( "cruise/cd44f8_83fc021174744c058d9cd308006ec097_mv2_bkkr0h", height: "400", width: "600", class: "d-block carousel-image") %>
              <div class="carousel-caption d-none d-md-block">
                <p>Traveling with us will leave you speechless, then turn you into a storyteller.</p>
              </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class = "d-flex flex-column align-items-center m-4">
        <p class="d-flex w-75" id="description">
          Paradise Cruises Mauritius, your online cruise travel company dedicated to providing customers with better deals than any other cruise website and access to great deals on cruise vacations.
          Offering special rates and savings on cruise bookings with some of the most popular cruise lines in the world, we are so confident in our cruise packages that each and every deal is backed by a price guarantee.
          You'll love where we take you!
        </p>
        <%= link_to "BOOK YOUR CRUISE NOW",  cruises_path, class: "btn btn-booknow card-link"%>
    </div>
  </div>
  <div class="d-flex row justify-content-evenly">
    <div class="col w-50 justify-content-center align-items-center" id="services">
      <ul>
        <li><i class="fas fa-street-view"></i> <p>Guides : our guides are professionally trained, experienced, hospitable and well groomed. We take great pride in being able to provide a large number of professional multi-lingual guides on our island. Our most important assets!</p></li>
        <li><i class="fas fa-shuttle-van"></i> <p>Transportation : we have excellent relationships with transport providers on both islands and maintain regular checks on both vehicles and drivers – constantly working to improve standards</p></li>
        <li><i class="far fa-calendar-check"></i><p> Timing of excursions : we update our tours according to traffic situations and other important factors to ensure timely stops and returns.</p></li>
      </ul>
    </div>
    <div class="col w-50 justify-content-center align-items-center">
        <%= render "pages/imagesvg" %>
        <figcaption class="figure-caption text-center">Paradise Cruises, Mauritius.</figcaption>
    </div>
  </div>
</div>

app/views/shared/_fidelity.html.erb
<h1>My fidelity Points</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="inner-header bg-info">
  <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  viewBox="10 24 150 25" preserveAspectRatio="none" shape-rendering="auto">
    <defs>
      <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
    </defs>
    <g class="parallax">
      <use xlink:href="#gentle-wave" x="70" y="0" fill="rgba(255,255,255,0.7" />
      <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
      <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
      <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
    </g>
  </svg>
  <div class = "d-flex flex-column justify-content-center contact">
    <div class = "d-inline">
      <ul>
          <li class="d-flex justify-content-center"> 
            <a href="#"><i class="fab fa-facebook-square"></i></a>
            <a href="#"><i class="fab fa-instagram-square"></i></a>
            <a href="#"><i class="fas fa-envelope-square"></i></a>
        </li>
      </ul>
    </div>
  </div>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar d-flex justify-content-between sticky-top navbar-expand-sm navbar-bg navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.is_owner? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cruises", cruises_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu navbar-bg dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "New cruises", new_cruise_path, class: "dropdown-item" %>
              <%= link_to "List Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cruises", cruises_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu navbar-bg dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My fidelity points", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cruises", cruises_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="mt-3">My fidelity points</h1>
<div class="container d-flex justify-content-center">
  <div class="row">
    <div class="col-lg-12" style="height: 50vh;" >
      <h3>We are very pleased to have you as one of our valued customers</h3>
      <p>This is why we have the pleasure to offer a Fidelity point accumulator upon every bookings made through our system.</p>
      <div class="d-flex justify-content-center align-items-center py-3">
        <h3 class="mr-4 py-3">Your Fidelity Point Total is actually:</h3>
        <h2 class="bg-success text-white px-4 py-2"><%= @fidelity_point.to_i %></h2>
      </div>
    </div>
  </div>
</div>